MACRO( source_group_tree )
	FILE( GLOB all_files ${ARGV1}/* )
	SET( files "" )
	FOREACH( each ${all_files} )
		IF( NOT IS_DIRECTORY ${each} )
			GET_FILENAME_COMPONENT( file_name ${each} NAME )
			LIST( APPEND files "${ARGV1}/${file_name}" )
		ENDIF()
	ENDFOREACH()
	LIST( LENGTH files files_len )
	IF( ${files_len} GREATER 0 )
		STRING( REPLACE "/" "\\\\" group_name ${ARGV0} )
		SOURCE_GROUP("${group_name}" FILES ${files})
	ENDIF()
		
	FILE( GLOB directories ${ARGV1}/*/ )
	FOREACH( each ${directories} )
		IF( IS_DIRECTORY ${each} )
			GET_FILENAME_COMPONENT( file_name ${each} NAME )
			source_group_tree("${ARGV0}/${file_name}" "${ARGV1}/${file_name}")
		ENDIF()
	ENDFOREACH()
ENDMACRO()
